excluded:
- Pods

line_length:
  warning: 300
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

force_cast: warning

type_body_length:
  warning: 750
  error: 800

file_length:
  warning: 1000
  error: 1050

cyclomatic_complexity:
  ignores_case_statements: true

disabled_rules:
- implicit_getter


